### PR TITLE
Centered h2 text and removed useless CSS code  (last pr i hope)

### PR DESCRIPTION
**Pull request by Tarkan-Zarrouk**
There was bloatly HTML code that I deleted (I couldn't find a single use for it anywhere + you had linked in as your StackOverflow)

### CODE REVIEW

**Comment by Tarkan-Zarrouk** [comment]
also, use bootstrap for your nav pannel, it's very good lol

**Comment by Zane2b2t** [comment]
I agre

**Comment by Gentleman2292** [comment]
ok

**Comment by Gentleman2292** [comment]
sorry for being such a bozo

**Pull request merged**
