### PR TITLE
General fixes

### PR DESCRIPTION
**Pull request by Tarkan-Zarrouk**
Please learn HTML before you actually Skid an HTML Project, this is just sad

Do you even know what the hell you're doing? Instead of trying to dump clients learn HTML, CSS, and JS for once

### CODE REVIEW

**Comment by Tarkan-Zarrouk** [comment]
dont merge yet, im still making some things look better

**Comment by Tarkan-Zarrouk** [comment]
image
current view 72% via browser after commits
image
current view 72% via browser after commits

**Comment by Tarkan-Zarrouk** [comment]
All I did was fix some grammar issues and changed size box to improve clairty.

**Comment by Tarkan-Zarrouk** [comment]
dont merge yet, just going to fix something lol

**Comment by Gentleman2292** [comment]
ayy thanks

**Comment by Gentleman2292** [comment]
i was inactive due to some irl shits

**Comment by Gentleman2292** [comment]
ill merge

**Comment by Gentleman2292** [comment]
thanks

**Pull request merged**
